output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

# SEE: https://golangci-lint.run/usage/configuration/
linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
  varnamelen:
    max-distance: 5
    min-name-length: 3
    check-receiver: false
    check-return: false
    check-type-param: false
    ignore-type-assert-ok: false
    ignore-map-index-ok: false
    ignore-chan-recv-ok: false
    ignore-names:
      - err
      - to
      - db
      - i
      - j
    ignore-decls:
      - c echo.Context
      - e *echo.Echo
      - s Server
  godox:
    keywords:
      - "BUG"
      - "FIXME"
    #  - "TODO"

linters:
  enable-all: true
  disable:
    - exportloopref # is deprecated (since v1.60.2)
    - exhaustruct # mad linter
    - wrapcheck # mad linter
    - nonamedreturns

issues:
  exclude:

  exclude-rules:

  exclude-dirs:
    - vendor/
  exclude-files:
    - ".*_test.go$"
